yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path("group/<slug>/", views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
SYMBOL_CONST = 15


class Post(models.Model):
    text = models.TextField(
        'Заголовок',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:SYMBOL_CONST]


class Group(models.Model):
    title = models.CharField("Title", max_length=200)
    slug = models.SlugField("Slug", max_length=200, unique=True)
    description = models.TextField("Description", null=True, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField('Текст', help_text='Текст нового комментария')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа'
        }
        help_text = {
            'text': 'Текст нового поста',
            'group': 'Группа к которой будет относиться пост'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from posts.forms import PostForm, CommentForm
from .models import Follow, Group, Post, User
from django.views.decorators.cache import cache_page

CONST_POST = 10


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.select_related('group', 'author').all()
    paginator = Paginator(posts, CONST_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group')
    paginator = Paginator(posts, CONST_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related("author")
    count = author.posts.count()
    paginator = Paginator(posts, CONST_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    follow = (request.user.is_authenticated and author != request.user
              and Follow.objects.filter(
                  author=author,
                  user=request.user).exists())
    context = {
        'count': count,
        'page_obj': page_obj,
        'author': author,
        'following': follow,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    pub_date = post.pub_date
    post_title = post.text[:30]
    author = post.author
    author_posts = author.posts.all().count()
    form_comment = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'post_title': post_title,
        'author': author,
        'author_posts': author_posts,
        'pub_date': pub_date,
        'comments': comments,
        'form_comment': form_comment,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/post_create.html', {"form": form})


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        "form": form,
        "post": post,
        "is_edit": is_edit,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, CONST_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Главная страница{% endblock %}
{% block content %}
  {% cache 20 index_page %}
  {% for post in page_obj %}
  {% include 'posts/includes/switcher.html' %}
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Список постов {{ group.title }}{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{group.description}}</p>
      {% for post in posts %}
      <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
   <p>{{ post.text }}</p>
   {% if post.group %}
  {% endif %}
   {% if not forloop.last %}<hr>{% endif %}
  </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page %}
  {% for post in page_obj %}  
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} Редактировать {% else %} Новый пост {% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %} Редактировать {% else %} Новый пост {% endif %}             
              </div>
              <div class="card-body">
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      <div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}
                <form method="post" enctype="multipart/form-data" action={% if is_edit %} "{% url 'posts:post_edit' post_id=post.pk %}" {% else %} "{% url 'posts:post_create' %}" {% endif %}>
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for={{ field.id_for_label }}>
                      {{ field.label }}
                      {% if field.field.required %}
                      <span class="required text-danger" >*</span> 
                      {% endif %}                 
                    </label>
                    {{ field }}
                    {% if field.text %}                
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.text|safe }}
                    </small>
                    {% endif %}            
                  </div>
                  {% endfor %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                    </label>
                    {% for group in group %}
                      <option value="1">
                      {{ group }}
                      </option>
                    {% endfor %}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Добавить
                        {% else %}
                          Сохранить
                        {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>  
            <li class="list-group-item">
              Группа: {{ post.group }}
              {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
                {% if post.group %}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
              </a>
                {% endif %}
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}
        </article>
      </div> 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ user }}{% endblock %}
{% block content %}
{% load thumbnail %}
    <div class="container py-5">
      <h1>Все посты пользователя {{ user }} </h1>
      <h3>Всего постов: {{ count }} </h3>
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор:
            <a href="{% url 'posts:profile' post.author.username %}">{{ author }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <ul>
          <li>
            {% if post.author  %}
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            {% endif %}
          </li>
          <li>
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
          </li>
        </ul>
      <hr>
      {% if not forloop.last %}
      {% endif %}
      </article>
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}